#!/bin/bash
#
# yafdb - Yet Another Face Detection and Bluring
#
# Copyright (c) 2014 FOXEL SA - http://foxel.ch
# Please read <http://foxel.ch/license> for more information.
#
#
# Author(s):
#
#      Kevin Velickovic <k.velickovic@foxel.ch>
#
#
# This file is part of the FOXEL project <http://foxel.ch>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Additional Terms:
#
#      You are required to preserve legal notices and author attributions in
#      that material or in the Appropriate Legal Notices displayed by works
#      containing it.
#
#      You are required to attribute the work as explained in the "Usage and
#      Attribution" section of <http://foxel.ch/license>.

# Check presence of GNU parallel
if ! which parallel >/dev/null; then
    echo "GNU parallel not installed, please install it with 'sudo apt-get install parallel'"
    exit
fi

# Arguments check
if [ $# -eq 0 ]
  then
    echo "Usage: $0 <HAAR cascades folder>"
    exit
fi

# Cleanning useless slashes from input path
HAAR_PATH=$(echo $1 | sed s#//*#/#g)

# Start detection
echo "Detecting objects"
find ../ -iname "*.tif" | parallel --eta -j1 yafdb-detect --algorithm haar \
        --gnomonic --gnomonic-width 2048 --gnomonic-aperture-x 90 --gnomonic-aperture-y 90 \
        --haar-model front:$HAAR_PATH/front-face.xml:1:-1 \
        --haar-model eyes:$HAAR_PATH/eyes.xml:front:0:-1 \
        --haar-model nose:$HAAR_PATH/nose.xml:front:0:-1 \
        --haar-model profile:$HAAR_PATH/profile-face.xml:1:-1 \
        --haar-model eyes:$HAAR_PATH/eyes.xml:profile:0:-1 \
        --haar-model nose:$HAAR_PATH/nose.xml:profile:0:-1 \
        "../{/.}.tif" "yml_configs/{/.}.yml"
