#!/bin/bash
#
# yafdb - Yet Another Face Detection and Bluring
#
# Copyright (c) 2014 FOXEL SA - http://foxel.ch
# Please read <http://foxel.ch/license> for more information.
#
#
# Author(s):
#
#      Kevin Velickovic <k.velickovic@foxel.ch>
#
#
# This file is part of the FOXEL project <http://foxel.ch>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Additional Terms:
#
#      You are required to preserve legal notices and author attributions in
#      that material or in the Appropriate Legal Notices displayed by works
#      containing it.
#
#      You are required to attribute the work as explained in the "Usage and
#      Attribution" section of <http://foxel.ch/license>.

# Arguments check
if [ $# -eq 0 ]
  then
    echo "Usage: $0 <timestamp> [Base Path]"
    exit
fi

# Switch to base path if specified
if [[ ! -z $2 ]]; then
    BASE_PATH=$(echo $2 | sed s#//*#/#g)
    cd $BASE_PATH
fi

# Check for base directories presence
if [ ! -d "yml_configs/" ]; then
  echo "Directory yml_configs not found, are you in a 'blurring' yafdb directory ?"
  exit
fi

# Start validation
yafdb-validate --fullscreen --auto-validate --gnomonic \
../result_$1.tif yml_configs/result_$1.yml yml_configs/result_$1.yml
